### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by ghost** [disposable/disposable#86] opened 2022-08-18 08:10 UTC
Hello!

simplelogin.com
simplelogin.fr
aleeas.com
smail.me 
pm.me

I can see that you’d service think that it is a temporary mail, but it is NOT.

The SimpleLogin service (https://simplelogin.io/) is designed to hide a user's real email address, and protect it from spam. All addresses created by SimpleLogin are perfectly normal and have the ability to both receive and send emails.

Also, all of them are owned by the most famous encrypted email provider Proton AG (https://proton.me, ex [https://protonmail.com)]https://protonmail.com). You can check it just by Whois.

Please unblock the mail domains I indicated above

**Comment by jasonkarns** [comment] 2023-06-19 19:22
Unfortunately, it seems others are trying to go even further and block _more_ simplelogins :/ #95 😞

**Comment by jasonkarns** [comment] 2023-06-19 19:33
simplelogin is also noted on #81

**Comment by smeinecke** [comment] 2023-09-20 22:06
Duplicate of #81

**Closed by smeinecke** 2023-09-20 22:06 UTC
Labels: duplicate
