### ISSUE TITLE
Add: Simplelogin.com

### ISSUE THREAD

**Issue by Fossil01** [disposable/disposable#95] opened 2023-03-05 17:03 UTC
https://simplelogin.io/

Has many aliases. Here's a few:

simplelogin.com
simplelogin.io
simplelogin.fr
aleeas.com
8alias.com
dralias.com
slmail.me
8shield.net

If someone has an account there they might be able to provide the full list: https://simplelogin.io/docs/custom-domain/manage-domain/

**Comment by jasonkarns** [comment] 2023-06-19 19:20
Simplelogin is an alias, not temporary or disposable. Like apple's own Hide My Email

**Comment by smeinecke** [comment] 2023-09-20 22:05
Duplicate of #86.

**Closed by smeinecke** 2023-09-20 22:05 UTC
Labels: duplicate
